// You can add more skin types here following the same pattern
export const skinTypeColors = {
	DSPT: {
		bgColor: "#C469A7",
		titleColor: "#fff",
		indexColor: "#FDE6FF",
		descColor: "#FDE6FF",
		disabledOpacity: 0.5,
	},
	DSNT: {
		bgColor: "#F499C1",
		titleColor: "#222",
		indexColor: "#333",
		descColor: "#333",
		disabledOpacity: 0.5,
	},
	DSPW: {
		bgColor: "#F06788",
		titleColor: "#fff",
		indexColor: "#fff5f5",
		descColor: "#fff5f5",
		disabledOpacity: 0.5,
	},
	DSNW: {
		bgColor: "#F3B5A8",
		titleColor: "#442c2c",
		indexColor: "#4a2f2f",
		descColor: "#4a2f2f",
		disabledOpacity: 0.5,
	},
	OSPT: {
		bgColor: "#F6976E",
		titleColor: "#fff",
		indexColor: "#fff3ed",
		descColor: "#fff3ed",
		disabledOpacity: 0.5,
	},
	OSNT: {
		bgColor: "#FDD6B8",
		titleColor: "#4a2d1e",
		indexColor: "#4a2d1e",
		descColor: "#4a2d1e",
		disabledOpacity: 0.5,
	},
	OSPW: {
		bgColor: "#FCB95C",
		titleColor: "#4a3300",
		indexColor: "#4a3300",
		descColor: "#4a3300",
		disabledOpacity: 0.5,
	},
	OSNW: {
		bgColor: "#FFE3A4",
		titleColor: "#4a3900",
		indexColor: "#4a3900",
		descColor: "#4a3900",
		disabledOpacity: 0.5,
	},
	ORPT: {
		bgColor: "#B5D335",
		titleColor: "#333",
		indexColor: "#444",
		descColor: "#444",
		disabledOpacity: 0.5,
	},
	ORNT: {
		bgColor: "#CCE39D",
		titleColor: "#2c331e",
		indexColor: "#2c331e",
		descColor: "#2c331e",
		disabledOpacity: 0.5,
	},
	ORPW: {
		bgColor: "#83C15C",
		titleColor: "#1e3312",
		indexColor: "#1e3312",
		descColor: "#1e3312",
		disabledOpacity: 0.5,
	},
	ORNW: {
		bgColor: "#9FD6BC",
		titleColor: "#1c1c1c",
		indexColor: "#2a2a2a",
		descColor: "#2a2a2a",
		disabledOpacity: 0.5,
	},
	DRPT: {
		bgColor: "#46A5C4",
		titleColor: "#fff",
		indexColor: "#e4f9ff",
		descColor: "#e4f9ff",
		disabledOpacity: 0.5,
	},
	DRNT: {
		bgColor: "#9EC1E5",
		titleColor: "#253142",
		indexColor: "#2e3b4f",
		descColor: "#2e3b4f",
		disabledOpacity: 0.5,
	},
	DRPW: {
		bgColor: "#A892B2",
		titleColor: "#fff",
		indexColor: "#f7efff",
		descColor: "#f7efff",
		disabledOpacity: 0.5,
	},
	DRNW: {
		bgColor: "#C2B0CE",
		titleColor: "#2e2239",
		indexColor: "#3b2e4f",
		descColor: "#3b2e4f",
		disabledOpacity: 0.5,
	},
};

export const MBSTStyles = {
	container: {
		flex: 1,
		backgroundColor: "#f0f2f5", // Light gray background
		padding: 16,
	},
	centered: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	title: {
		fontSize: 24,
		fontWeight: "bold",
		textAlign: "center",
		marginBottom: 24,
		color: "#2c3e50", // Dark title color
	},
	resultBox: {
		borderRadius: 12,
		padding: 24,
		alignItems: "center",
		marginBottom: 24,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 5,
	},
	baumannTypeLabel: {
		fontSize: 18,
		fontWeight: "500",
		marginBottom: 4,
	},
	baumannType: {
		fontSize: 56,
		fontWeight: "900",
		letterSpacing: 1.5,
	},
	divider: {
		height: 1,
		backgroundColor: "#e0e0e0",
		marginVertical: 24,
	},
	partsSection: {
		marginBottom: 24,
	},
	dualBarSection: {
		marginBottom: 24,
	},
	dualBarLabel: {
		fontSize: 18,
		fontWeight: "600",
		color: "#34495e",
		marginBottom: 12,
		textAlign: "center",
	},
	dualBarContainer: {
		flexDirection: "row",
		width: "85%", // 80% 대신 제거하거나,
		alignSelf: "center", // <-- 이걸 추가하세요!
		alignItems: "center",
		height: 12,
		// justifyContent: 'center', // 없어도 됨
	},
	barWrapper: {
		flex: 1,
		height: "100%",
		backgroundColor: "#e0e0e0",
		borderRadius: 6,
		marginHorizontal: 12,
		overflow: "hidden",
	},
	dominantBar: {
		height: "100%",
		borderRadius: 6,
	},
	dualLabelText: {
		fontSize: 14,
		fontWeight: "500",
		color: "#7f8c8d",
		minWidth: 40,
	},
	dualScoreContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: 8,
	},
	dualScoreText: {
		fontSize: 14,
		fontWeight: "bold",
		color: "#34495e",
	},
	descriptionBox: {
		backgroundColor: "#ffffff",
		borderRadius: 12,
		padding: 24,
		marginBottom: 24,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.08,
		shadowRadius: 6,
		elevation: 3,
	},
	descriptionTitle: {
		fontSize: 22,
		fontWeight: "bold",
		marginBottom: 12,
		color: "#2c3e50",
	},
	descriptionText: {
		fontSize: 16,
		lineHeight: 24,
		color: "#34495e",
	},
	sectionBox: {
		marginBottom: 20,
		backgroundColor: "#f9f9f9",
		padding: 20,
		borderRadius: 10,
	},
	sectionTitle: {
		fontSize: 20,
		fontWeight: "bold",
		marginBottom: 10,
		color: "#2c3e50",
	},
	sectionText: {
		fontSize: 16,
		lineHeight: 24,
		color: "#555",
	},
	subTitle: {
		fontSize: 18,
		fontWeight: "600",
		marginTop: 10,
		marginBottom: 6,
		color: "#34495e",
	},
	bulletText: {
		fontSize: 16,
		lineHeight: 24,
		marginLeft: 8,
		color: "#555",
	},
	subSection: {
		marginBottom: 12,
	},
	noDataText: {
		fontSize: 18,
		color: "#7f8c8d",
	},
	byline: {
		fontSize: 12,
		color: "#95a5a6",
		textAlign: "right",
		marginTop: 16,
		fontStyle: "italic",
	},
	combinationBox: {
		backgroundColor: "#f1f1f1",
		borderRadius: 10,
		alignItems: "center",
	},
	combinationText: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#333",
		marginBottom: 10,
	},
	combinationDescriptionText: {
		fontSize: 16,
		color: "#444",
		lineHeight: 24,
		marginBottom: 12,
	},
	dualBarSection: {
		marginBottom: 32,
		alignItems: "center",
	},
	dualBarLabel: {
		fontSize: 18,
		fontWeight: "600",
		color: "#34495e",
		marginBottom: 8,
		textAlign: "center",
	},
	barWithPercentRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		width: "100%",
		gap: 8,
		marginBottom: 6,
	},
	percentLabel: {
		width: 40,
		textAlign: "center",
		fontSize: 13,
		fontWeight: "500",
		color: "#7f8c8d",
	},
	dualBarContainer: {
		flex: 1,
		height: 12,
		backgroundColor: "#e0e0e0",
		borderRadius: 6,
		overflow: "hidden",
		position: "relative",
	},
	barWrapper: {
		flex: 1,
		height: "100%",
	},
	dominantBar: {
		height: "100%",
		borderRadius: 6,
	},
	letterRow: {
		width: "80%",
		flexDirection: "row",
		justifyContent: "space-between",
	},
	alphabetLabel: {
		fontSize: 14,
		fontWeight: "bold",
		color: "#34495e",
	},
};

export default MBSTStyles;
